//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTinTucBan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiViet
    {
        public int ID { get; set; }
        public Nullable<int> ID_MucLuc { get; set; }
        public Nullable<int> ID_NguoiDang { get; set; }
        public string TieuDe { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public string NoiDung { get; set; }
        public string LinkThumbnail { get; set; }
        public Nullable<int> NgayDang { get; set; }
        public string LinkPDF { get; set; }
        public Nullable<int> NgayCapNhat { get; set; }
        public Nullable<int> ViewUpdate { get; set; }
    
        public virtual MucLuc MucLuc { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
