//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTinTucBan.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebTinTucTDMUEntities : DbContext
    {
        public WebTinTucTDMUEntities()
            : base("name=WebTinTucTDMUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaiViet> BaiViets { get; set; }
        public virtual DbSet<DonViTrucThuoc> DonViTrucThuocs { get; set; }
        public virtual DbSet<Khoi> Khois { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Menu_by_sub> Menu_by_sub { get; set; }
        public virtual DbSet<MucLuc> MucLucs { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Slider> Sliders { get; set; }
        public virtual DbSet<Sub_Menu> Sub_Menu { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
    }
}
