//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTinTucBan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonViTrucThuoc
    {
        public int ID { get; set; }
        public Nullable<int> ID_Khoi { get; set; }
        public string TenDonVi { get; set; }
        public Nullable<int> ThuTuShow { get; set; }
        public string Link { get; set; }
        public Nullable<int> NgayDang { get; set; }
        public Nullable<int> NgayCapNhat { get; set; }
        public Nullable<int> IsActive { get; set; }
    
        public virtual Khoi Khoi { get; set; }
    }
}
