//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTinTucBan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Footer
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public string EnglishName { get; set; }
        public Nullable<int> NgayThanhLap { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string Email { get; set; }
        public string VideoUrl { get; set; }
        public string FooterCopyright { get; set; }
        public string FooterNote { get; set; }
        public Nullable<int> NgayCapNhat { get; set; }
        public Nullable<int> NgayDang { get; set; }
    }
}
