//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTinTucBan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_by_sub
    {
        public int id { get; set; }
        public Nullable<int> id_menu { get; set; }
        public Nullable<int> id_sub { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Sub_Menu Sub_Menu { get; set; }
    }
}
