//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTinTucBan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu()
        {
            this.Function_By_Menu = new HashSet<Function_By_Menu>();
            this.Group_By_Menu_And_Sub = new HashSet<Group_By_Menu_And_Sub>();
            this.Menu_by_sub = new HashSet<Menu_by_sub>();
        }
    
        public int ID { get; set; }
        public string Ten { get; set; }
        public string Link { get; set; }
        public Nullable<int> ThuTuShow { get; set; }
        public Nullable<int> NgayDang { get; set; }
        public string IconName { get; set; }
        public Nullable<int> IsImportant { get; set; }
        public Nullable<int> NgayCapNhat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Function_By_Menu> Function_By_Menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group_By_Menu_And_Sub> Group_By_Menu_And_Sub { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu_by_sub> Menu_by_sub { get; set; }
    }
}
