//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTinTucBan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_Group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu_Group()
        {
            this.Group_By_Menu = new HashSet<Group_By_Menu>();
            this.Roles_By_Group = new HashSet<Roles_By_Group>();
        }
    
        public int ID { get; set; }
        public string Ten { get; set; }
        public Nullable<int> NgayTao { get; set; }
        public Nullable<int> NgayCapNhat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group_By_Menu> Group_By_Menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Roles_By_Group> Roles_By_Group { get; set; }
    }
}
