//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTinTucBan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyenUser
    {
        public int ID { get; set; }
        public Nullable<int> ID_Function { get; set; }
        public Nullable<int> ID_TaiKhoan { get; set; }
    
        public virtual ChucNangQuyenUser ChucNangQuyenUser { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
