//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTinTucBan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles_By_Group
    {
        public int ID { get; set; }
        public Nullable<int> ID_ROLES { get; set; }
        public Nullable<int> ID_GROUP { get; set; }
    
        public virtual Menu_Group Menu_Group { get; set; }
        public virtual Role Role { get; set; }
    }
}
