//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTinTucBan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sub_Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sub_Menu()
        {
            this.Menu_by_sub = new HashSet<Menu_by_sub>();
        }
    
        public int id_sub { get; set; }
        public string name_sub { get; set; }
        public Nullable<int> time_create { get; set; }
        public Nullable<int> time_update { get; set; }
        public string Link { get; set; }
        public Nullable<int> ThuTuShow { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menu_by_sub> Menu_by_sub { get; set; }
    }
}
