//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTinTucBan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiLieu
    {
        public int STT { get; set; }
        public string Ten_Tailieu { get; set; }
        public int Upload_Date { get; set; }
        public string Download_Link { get; set; }
    }
}
