//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTinTucBan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorLog
    {
        public int ID { get; set; }
        public Nullable<int> NgayTao { get; set; }
        public Nullable<int> TotalAmount { get; set; }
        public Nullable<int> CurrentActive { get; set; }
    }
}
